//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35317
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadifyServiceConsumer.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TriangleType", Namespace="http://KnockKnock.readify.net")]
    public enum TriangleType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Equilateral = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Isosceles = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Scalene = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMyRedPillService")]
    public interface IMyRedPillService {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://KnockKnock.readify.net) of message WhatIsYourTokenRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://KnockKnock.readify.net/IRedPill/WhatIsYourToken", ReplyAction="http://KnockKnock.readify.net/IRedPill/WhatIsYourTokenResponse")]
        ReadifyServiceConsumer.ServiceReference1.WhatIsYourTokenResponse WhatIsYourToken(ReadifyServiceConsumer.ServiceReference1.WhatIsYourTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://KnockKnock.readify.net/IRedPill/WhatIsYourToken", ReplyAction="http://KnockKnock.readify.net/IRedPill/WhatIsYourTokenResponse")]
        System.Threading.Tasks.Task<ReadifyServiceConsumer.ServiceReference1.WhatIsYourTokenResponse> WhatIsYourTokenAsync(ReadifyServiceConsumer.ServiceReference1.WhatIsYourTokenRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://KnockKnock.readify.net) of message FibonacciNumberRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://KnockKnock.readify.net/IRedPill/FibonacciNumber", ReplyAction="http://KnockKnock.readify.net/IRedPill/FibonacciNumberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentOutOfRangeException), Action="http://KnockKnock.readify.net/IRedPill/FibonacciNumberArgumentOutOfRangeException" +
            "Fault", Name="ArgumentOutOfRangeException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        ReadifyServiceConsumer.ServiceReference1.FibonacciNumberResponse FibonacciNumber(ReadifyServiceConsumer.ServiceReference1.FibonacciNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://KnockKnock.readify.net/IRedPill/FibonacciNumber", ReplyAction="http://KnockKnock.readify.net/IRedPill/FibonacciNumberResponse")]
        System.Threading.Tasks.Task<ReadifyServiceConsumer.ServiceReference1.FibonacciNumberResponse> FibonacciNumberAsync(ReadifyServiceConsumer.ServiceReference1.FibonacciNumberRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://KnockKnock.readify.net) of message WhatShapeIsThisRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://KnockKnock.readify.net/IRedPill/WhatShapeIsThis", ReplyAction="http://KnockKnock.readify.net/IRedPill/WhatShapeIsThisResponse")]
        ReadifyServiceConsumer.ServiceReference1.WhatShapeIsThisResponse WhatShapeIsThis(ReadifyServiceConsumer.ServiceReference1.WhatShapeIsThisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://KnockKnock.readify.net/IRedPill/WhatShapeIsThis", ReplyAction="http://KnockKnock.readify.net/IRedPill/WhatShapeIsThisResponse")]
        System.Threading.Tasks.Task<ReadifyServiceConsumer.ServiceReference1.WhatShapeIsThisResponse> WhatShapeIsThisAsync(ReadifyServiceConsumer.ServiceReference1.WhatShapeIsThisRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://KnockKnock.readify.net) of message ReverseWordsRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://KnockKnock.readify.net/IRedPill/ReverseWords", ReplyAction="http://KnockKnock.readify.net/IRedPill/ReverseWordsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentNullException), Action="http://KnockKnock.readify.net/IRedPill/ReverseWordsArgumentNullExceptionFault", Name="ArgumentNullException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        ReadifyServiceConsumer.ServiceReference1.ReverseWordsResponse ReverseWords(ReadifyServiceConsumer.ServiceReference1.ReverseWordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://KnockKnock.readify.net/IRedPill/ReverseWords", ReplyAction="http://KnockKnock.readify.net/IRedPill/ReverseWordsResponse")]
        System.Threading.Tasks.Task<ReadifyServiceConsumer.ServiceReference1.ReverseWordsResponse> ReverseWordsAsync(ReadifyServiceConsumer.ServiceReference1.ReverseWordsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WhatIsYourToken", WrapperNamespace="http://KnockKnock.readify.net", IsWrapped=true)]
    public partial class WhatIsYourTokenRequest {
        
        public WhatIsYourTokenRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WhatIsYourTokenResponse", WrapperNamespace="http://KnockKnock.readify.net", IsWrapped=true)]
    public partial class WhatIsYourTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KnockKnock.readify.net", Order=0)]
        public System.Guid WhatIsYourTokenResult;
        
        public WhatIsYourTokenResponse() {
        }
        
        public WhatIsYourTokenResponse(System.Guid WhatIsYourTokenResult) {
            this.WhatIsYourTokenResult = WhatIsYourTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FibonacciNumber", WrapperNamespace="http://KnockKnock.readify.net", IsWrapped=true)]
    public partial class FibonacciNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KnockKnock.readify.net", Order=0)]
        public long n;
        
        public FibonacciNumberRequest() {
        }
        
        public FibonacciNumberRequest(long n) {
            this.n = n;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FibonacciNumberResponse", WrapperNamespace="http://KnockKnock.readify.net", IsWrapped=true)]
    public partial class FibonacciNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KnockKnock.readify.net", Order=0)]
        public long FibonacciNumberResult;
        
        public FibonacciNumberResponse() {
        }
        
        public FibonacciNumberResponse(long FibonacciNumberResult) {
            this.FibonacciNumberResult = FibonacciNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WhatShapeIsThis", WrapperNamespace="http://KnockKnock.readify.net", IsWrapped=true)]
    public partial class WhatShapeIsThisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KnockKnock.readify.net", Order=0)]
        public int a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KnockKnock.readify.net", Order=1)]
        public int b;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KnockKnock.readify.net", Order=2)]
        public int c;
        
        public WhatShapeIsThisRequest() {
        }
        
        public WhatShapeIsThisRequest(int a, int b, int c) {
            this.a = a;
            this.b = b;
            this.c = c;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WhatShapeIsThisResponse", WrapperNamespace="http://KnockKnock.readify.net", IsWrapped=true)]
    public partial class WhatShapeIsThisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KnockKnock.readify.net", Order=0)]
        public ReadifyServiceConsumer.ServiceReference1.TriangleType WhatShapeIsThisResult;
        
        public WhatShapeIsThisResponse() {
        }
        
        public WhatShapeIsThisResponse(ReadifyServiceConsumer.ServiceReference1.TriangleType WhatShapeIsThisResult) {
            this.WhatShapeIsThisResult = WhatShapeIsThisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReverseWords", WrapperNamespace="http://KnockKnock.readify.net", IsWrapped=true)]
    public partial class ReverseWordsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KnockKnock.readify.net", Order=0)]
        public string s;
        
        public ReverseWordsRequest() {
        }
        
        public ReverseWordsRequest(string s) {
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReverseWordsResponse", WrapperNamespace="http://KnockKnock.readify.net", IsWrapped=true)]
    public partial class ReverseWordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KnockKnock.readify.net", Order=0)]
        public string ReverseWordsResult;
        
        public ReverseWordsResponse() {
        }
        
        public ReverseWordsResponse(string ReverseWordsResult) {
            this.ReverseWordsResult = ReverseWordsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyRedPillServiceChannel : ReadifyServiceConsumer.ServiceReference1.IMyRedPillService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyRedPillServiceClient : System.ServiceModel.ClientBase<ReadifyServiceConsumer.ServiceReference1.IMyRedPillService>, ReadifyServiceConsumer.ServiceReference1.IMyRedPillService {
        
        public MyRedPillServiceClient() {
        }
        
        public MyRedPillServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyRedPillServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyRedPillServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyRedPillServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReadifyServiceConsumer.ServiceReference1.WhatIsYourTokenResponse ReadifyServiceConsumer.ServiceReference1.IMyRedPillService.WhatIsYourToken(ReadifyServiceConsumer.ServiceReference1.WhatIsYourTokenRequest request) {
            return base.Channel.WhatIsYourToken(request);
        }
        
        public System.Guid WhatIsYourToken() {
            ReadifyServiceConsumer.ServiceReference1.WhatIsYourTokenRequest inValue = new ReadifyServiceConsumer.ServiceReference1.WhatIsYourTokenRequest();
            ReadifyServiceConsumer.ServiceReference1.WhatIsYourTokenResponse retVal = ((ReadifyServiceConsumer.ServiceReference1.IMyRedPillService)(this)).WhatIsYourToken(inValue);
            return retVal.WhatIsYourTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReadifyServiceConsumer.ServiceReference1.WhatIsYourTokenResponse> ReadifyServiceConsumer.ServiceReference1.IMyRedPillService.WhatIsYourTokenAsync(ReadifyServiceConsumer.ServiceReference1.WhatIsYourTokenRequest request) {
            return base.Channel.WhatIsYourTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReadifyServiceConsumer.ServiceReference1.WhatIsYourTokenResponse> WhatIsYourTokenAsync() {
            ReadifyServiceConsumer.ServiceReference1.WhatIsYourTokenRequest inValue = new ReadifyServiceConsumer.ServiceReference1.WhatIsYourTokenRequest();
            return ((ReadifyServiceConsumer.ServiceReference1.IMyRedPillService)(this)).WhatIsYourTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReadifyServiceConsumer.ServiceReference1.FibonacciNumberResponse ReadifyServiceConsumer.ServiceReference1.IMyRedPillService.FibonacciNumber(ReadifyServiceConsumer.ServiceReference1.FibonacciNumberRequest request) {
            return base.Channel.FibonacciNumber(request);
        }
        
        public long FibonacciNumber(long n) {
            ReadifyServiceConsumer.ServiceReference1.FibonacciNumberRequest inValue = new ReadifyServiceConsumer.ServiceReference1.FibonacciNumberRequest();
            inValue.n = n;
            ReadifyServiceConsumer.ServiceReference1.FibonacciNumberResponse retVal = ((ReadifyServiceConsumer.ServiceReference1.IMyRedPillService)(this)).FibonacciNumber(inValue);
            return retVal.FibonacciNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReadifyServiceConsumer.ServiceReference1.FibonacciNumberResponse> ReadifyServiceConsumer.ServiceReference1.IMyRedPillService.FibonacciNumberAsync(ReadifyServiceConsumer.ServiceReference1.FibonacciNumberRequest request) {
            return base.Channel.FibonacciNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReadifyServiceConsumer.ServiceReference1.FibonacciNumberResponse> FibonacciNumberAsync(long n) {
            ReadifyServiceConsumer.ServiceReference1.FibonacciNumberRequest inValue = new ReadifyServiceConsumer.ServiceReference1.FibonacciNumberRequest();
            inValue.n = n;
            return ((ReadifyServiceConsumer.ServiceReference1.IMyRedPillService)(this)).FibonacciNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReadifyServiceConsumer.ServiceReference1.WhatShapeIsThisResponse ReadifyServiceConsumer.ServiceReference1.IMyRedPillService.WhatShapeIsThis(ReadifyServiceConsumer.ServiceReference1.WhatShapeIsThisRequest request) {
            return base.Channel.WhatShapeIsThis(request);
        }
        
        public ReadifyServiceConsumer.ServiceReference1.TriangleType WhatShapeIsThis(int a, int b, int c) {
            ReadifyServiceConsumer.ServiceReference1.WhatShapeIsThisRequest inValue = new ReadifyServiceConsumer.ServiceReference1.WhatShapeIsThisRequest();
            inValue.a = a;
            inValue.b = b;
            inValue.c = c;
            ReadifyServiceConsumer.ServiceReference1.WhatShapeIsThisResponse retVal = ((ReadifyServiceConsumer.ServiceReference1.IMyRedPillService)(this)).WhatShapeIsThis(inValue);
            return retVal.WhatShapeIsThisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReadifyServiceConsumer.ServiceReference1.WhatShapeIsThisResponse> ReadifyServiceConsumer.ServiceReference1.IMyRedPillService.WhatShapeIsThisAsync(ReadifyServiceConsumer.ServiceReference1.WhatShapeIsThisRequest request) {
            return base.Channel.WhatShapeIsThisAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReadifyServiceConsumer.ServiceReference1.WhatShapeIsThisResponse> WhatShapeIsThisAsync(int a, int b, int c) {
            ReadifyServiceConsumer.ServiceReference1.WhatShapeIsThisRequest inValue = new ReadifyServiceConsumer.ServiceReference1.WhatShapeIsThisRequest();
            inValue.a = a;
            inValue.b = b;
            inValue.c = c;
            return ((ReadifyServiceConsumer.ServiceReference1.IMyRedPillService)(this)).WhatShapeIsThisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReadifyServiceConsumer.ServiceReference1.ReverseWordsResponse ReadifyServiceConsumer.ServiceReference1.IMyRedPillService.ReverseWords(ReadifyServiceConsumer.ServiceReference1.ReverseWordsRequest request) {
            return base.Channel.ReverseWords(request);
        }
        
        public string ReverseWords(string s) {
            ReadifyServiceConsumer.ServiceReference1.ReverseWordsRequest inValue = new ReadifyServiceConsumer.ServiceReference1.ReverseWordsRequest();
            inValue.s = s;
            ReadifyServiceConsumer.ServiceReference1.ReverseWordsResponse retVal = ((ReadifyServiceConsumer.ServiceReference1.IMyRedPillService)(this)).ReverseWords(inValue);
            return retVal.ReverseWordsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReadifyServiceConsumer.ServiceReference1.ReverseWordsResponse> ReadifyServiceConsumer.ServiceReference1.IMyRedPillService.ReverseWordsAsync(ReadifyServiceConsumer.ServiceReference1.ReverseWordsRequest request) {
            return base.Channel.ReverseWordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReadifyServiceConsumer.ServiceReference1.ReverseWordsResponse> ReverseWordsAsync(string s) {
            ReadifyServiceConsumer.ServiceReference1.ReverseWordsRequest inValue = new ReadifyServiceConsumer.ServiceReference1.ReverseWordsRequest();
            inValue.s = s;
            return ((ReadifyServiceConsumer.ServiceReference1.IMyRedPillService)(this)).ReverseWordsAsync(inValue);
        }
    }
}
